# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOjYNE-qguzb6HCjcJpmDogzkTIZcVH1
"""



import streamlit as st
import numpy as np

st.title("Media Pembelajaran: Konsep Perkalian Matriks")

st.write("""
Perkalian matriks adalah operasi matematika di mana elemen baris dari matriks pertama dikalikan dengan elemen kolom dari matriks kedua dan hasilnya dijumlahkan.
\n
Aturan penting: jika matriks A berukuran (m × n), maka matriks B harus berukuran (n × p) agar perkalian A × B bisa dilakukan.
""")

# Input ukuran matriks A dan B
st.header("Masukkan ukuran matriks")

m = st.number_input("Jumlah baris matriks A (m)", min_value=1, max_value=5, value=2, step=1)
n = st.number_input("Jumlah kolom matriks A dan baris matriks B (n)", min_value=1, max_value=5, value=2, step=1)
p = st.number_input("Jumlah kolom matriks B (p)", min_value=1, max_value=5, value=2, step=1)

# Fungsi untuk input matriks
def input_matrix(rows, cols, name):
    st.write(f"Masukkan elemen matriks {name} (ukuran {rows}x{cols}):")
    matrix = []
    for i in range(rows):
        row = []
        cols_input = st.columns(cols)
        for j in range(cols):
            val = cols_input[j].number_input(f"{name}[{i+1},{j+1}]", value=0, key=f"{name}_{i}_{j}")
            row.append(val)
        matrix.append(row)
    return np.array(matrix)

# Input matriks A dan B
matrix_A = input_matrix(m, n, "A")
matrix_B = input_matrix(n, p, "B")

# Tampilkan matriks A dan B
st.subheader("Matriks A")
st.write(matrix_A)

st.subheader("Matriks B")
st.write(matrix_B)

# Perkalian matriks dengan penjelasan langkah
def multiply_matrices_with_steps(A, B):
    m, n = A.shape
    n2, p = B.shape
    assert n == n2, "Dimensi matriks tidak cocok untuk perkalian"

    result = np.zeros((m, p))
    steps = []
    for i in range(m):
        for j in range(p):
            step_detail = []
            for k in range(n):
                step_detail.append(f"A[{i+1},{k+1}]×B[{k+1},{j+1}] = {A[i,k]}×{B[k,j]}")
                result[i, j] += A[i, k] * B[k, j]
            steps.append((i, j, step_detail, result[i, j]))
    return result, steps

# Jika tombol klik untuk hitung
if st.button("Hitung Perkalian Matriks A × B"):
    try:
        result_matrix, calculation_steps = multiply_matrices_with_steps(matrix_A, matrix_B)
        st.subheader("Hasil Perkalian Matriks A × B:")
        st.write(result_matrix)

        st.subheader("Langkah-langkah Perhitungan:")
        for i, j, step_detail, value in calculation_steps:
            st.write(f"Elemen hasil [{i+1},{j+1}]:")
            for step in step_detail:
                st.write(" - " + step)
            st.write(f"Jumlahkan hasil: {value}")
            st.write("---")

    except AssertionError as e:
        st.error(str(e))